apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: awproduct-to-generic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: awproduct-to-generic
        app: awproduct-to-generic
    spec:
      containers:
      - name: awproduct-togeneric
        image: jbreedijk/awproduct.to.generic:2
        env:
          - name: RabbitConnection__Hostname
            value: rabbitmq
          - name: spring.rabbitmq.port
            value: "5672" 
          - name: RabbitConnection__Username
            value: utilize
          - name: RabbitConnection__Password
            value: utilize
          - name: RabbitConnection__Password
            value: redis


