apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sftp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sftp
        app: sftp
    spec:
      containers:
      - name: sftp
        image: jbreedijk/sftp-reader:latest
        env:
          - name: spring.rabbitmq.host
            value: rabbitmq
          - name: spring.rabbitmq.port
            value: "5672" 
          - name: spring.rabbitmq.user
            value: utilize
          - name: spring.rabbitmq.password
            value: utilize
          - name: spring.rabbitmq.queue
            value: sftp-read-jobs
          - name: spring.rabbitmq.exchange
            value: jobs


