apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: jenkins

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jenkins
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jbreedijk/jenkins-dotnet
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        - name: other
          containerPort: 5000
          protocol: TCP

