apiVersion: v1
kind: Service
metadata:
  name: konga
spec:
  ports:
  - name: konga
    port: 1337
    targetPort: 1337
    protocol: TCP
  selector:
    app: kong
  externalIPs:
    - 79.143.188.159
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        env:
          - name: NODE_ENV
            value: development
        ports:
        - name: interface
          containerPort: 1337
          protocol: TCP