apiVersion: v1
kind: Service
metadata:
  name: postgres-external
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: http
      protocol: TCP
  selector:
    app: postgres
  externalIPs:
    - 79.143.188.159

