apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - name: web
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
  externalIPs:
    - 79.143.188.159

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        ports:
        - name: default
          containerPort: 6379
          protocol: TCP
	    volumeMounts:
	      - name: xchange
	        mountPath: "/data"
  volumes:
  - name: xchange
    emptyDir: {}
